version: '3'


services:

  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./page:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles